version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: pp_liveview 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: pp_liveview
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

